// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cktqgcmcqikkgaazrhbs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNrdHFnY21jcWlra2dhYXpyaGJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI0MzM5MDMsImV4cCI6MjA3ODAwOTkwM30.PS4YynuI2NSzzZiS81aaxJoVXcyKFtRG9jSHyemC-ng";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});